version: '2.3'

services:
  minideb:
    build:
      context: . 
      dockerfile: Dockerfile.stretch
    image: djschaper/bats-core:latest
  alpine:
    build:
      context: .
      dockerfile: Dockerfile.alpine
    image: djschaper/bats-core:latest-alpine
